set -g status-style bg=default,fg=colour240
set -g mouse on
set-option -g status-position top
set -g status-style bg=default,fg=white
set -g set-titles on
set -g set-titles-string "#T"
set-option -g destroy-unattached on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"
bind-key -n MouseDown2Pane run "xclip -o -selection clipboard | tmux load-buffer - ; tmux paste-buffer"
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection primary -f -i | xclip -selection clipboard -i"
set -g status-right "%I:%M %p | %Y-%b-%d"
